In [245]:
import numpy as np
import pandas as pd
class Kohonen(object):
    
    def __init__(self, layer_size, epochs, sigma, alpha):
        self.ls = layer_size
        self.epochs = epochs
        self.sigma = sigma
        self.alpha = alpha

    
    def architecture(self):
        self.w = np.random.uniform(-0.5, 0.5, size=(self.ls, self.ls, self.xs))
        self.tal = self.epochs/np.log(self.sigma)
#         self.w = xala.copy()
#         self.w = np.array([[0.2, 0.6, 0.5, 0.9], [0.8, 0.4, 0.7, 0.3]])
        
    
    def train(self, X):
        self.xs = X.shape[1]
        self.architecture()
        alpha = self.alpha
        sigma = self.sigma
        for epoch in range(self.epochs):
            for x in X:
                D = np.sum(np.power(x-self.w, 2), axis=2)
                J = D.argmin()
                J = np.unravel_index(D.argmin(), D.shape)

                a, b = np.meshgrid(np.linspace(0,self.ls,self.ls)-J[1], np.linspace(0,self.ls,self.ls)-J[0])
                d = np.sqrt(a*a+b*b)
                radial = np.exp(-( (d)**2 / ( 2.0 * sigma**2 ) ) )
                self.w += alpha*np.dot(radial, (x-self.w))
            sigma = self.sigma*np.exp(-epoch/self.tal)
            alpha = self.alpha*np.exp(-epoch/self.tal)
    
    
x = np.array([[1, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0],[0, 0, 1, 1]])

sigma = 5
alpha = 0.6
layer_size = 4
epochs = 100

SOM = Kohonen(layer_size, epochs, sigma, alpha)
SOM.train(x)
print(SOM.w)

[[[ -1195.81621479  -2062.88243581  -1475.40145447   -573.32830245]
  [  -232.50813015   -437.29540298   -399.23521619   -199.48415154]
  [  1183.28657623   1968.15306991   1372.06683115    564.81052591]
  [  2779.30509319   5120.11470514   4130.76067952   1722.40026243]]

 [[   993.67195592   1987.0777284    1837.86805726    851.51763471]
  [  -149.13579909   -323.99072496   -353.74433312   -193.26559411]
  [ -1601.21682826  -3131.23552386  -2731.46211147  -1170.8813024 ]
  [  1070.33445272   2108.99602513   1820.75246391    784.286464  ]]

 [[  4921.56070432   9148.07950717   7575.87708344   3289.00040431]
  [   -52.94926278   -207.92625937   -322.02125812   -192.56911352]
  [ -6897.21072283 -12725.81558016 -10346.87512519  -4379.39202972]
  [ -2850.11335074  -4840.12298239  -3540.88089522  -1407.56917907]]

 [[  3622.9194119    6705.20865967   5530.16141724   2389.54978365]
  [   -41.58310378   -160.58946742   -249.87833281   -151.68137673]
  [ -5035.12061565  -9281.38318982  -7537.

In [246]:
from sklearn import datasets
wine = datasets.load_wine()
wine = pd.DataFrame(data= np.c_[wine['data'], wine['target']], columns= wine['feature_names'] + ['target'])
x = wine[wine.columns[:-1]].values


sigma = 5
alpha = 0.1
layer_size = 10
epochs = 10

SOM = Kohonen(layer_size, epochs, sigma, alpha)
SOM.train(x)
print(SOM.w)

[[[ 2.05619564e+17 -4.02984949e+15  3.85085030e+16 ...  3.41011586e+16
    6.37597706e+16  2.27575517e+19]
  [ 2.74958887e+16 -5.38880109e+14  5.14943954e+15 ...  4.56007999e+15
    8.52609316e+15  3.04318858e+18]
  [-4.15106411e+17  8.13549219e+15 -7.77412721e+16 ... -6.88436901e+16
   -1.28718732e+17 -4.59431264e+19]
  ...
  [-1.19759134e+18  2.34710781e+16 -2.24285320e+17 ... -1.98615595e+17
   -3.71356439e+17 -1.32546954e+20]
  [-1.16282376e+18  2.27896833e+16 -2.17774036e+17 ... -1.92849536e+17
   -3.60575496e+17 -1.28698950e+20]
  [-8.20140659e+17  1.60735844e+16 -1.53596226e+17 ... -1.36016953e+17
   -2.54314226e+17 -9.07714865e+19]]

 [[ 2.70094538e+17 -5.29346680e+15  5.05833985e+16 ...  4.47940677e+16
    8.37525645e+16  2.98935097e+19]
  [ 1.20756671e+17 -2.36665812e+15  2.26153512e+16 ...  2.00269970e+16
    3.74449664e+16  1.33651008e+19]
  [-2.53942481e+17  4.97690957e+15 -4.75584356e+16 ... -4.21153155e+16
   -7.87440359e+16 -2.81058331e+19]
  ...
  [-1.03227770e+18  2.0