## Bidirectional Associative Memory


In [108]:
import numpy as np

# Gerando exemplos aleatórios
# Numero de exemplos
n = 2
# Tamanho de exemplos de entrada
h = 10
# Tamanho de exemplos de saída
l = 7

X = np.random.randint(2, size=n*h).reshape((n, h))
X[X == 0] = -1

Y = np.random.randint(2, size=n*l).reshape((n, l))
Y[Y == 0] = -1


In [110]:
# Função aplicada sobre a saida da BAM
def f_net(net):
    net[net > 0] = +1
    net[net < 0] = -1
    net[net == 0] = -1 if (np.random.rand() < 0.5) else 1
    return net

# Calculo da matriz de correlação
def bam(X, Y):
    M = np.dot(X.T, Y)
    return M


# Avaliando o modelo
def bam_evaluate(x, M):
    y = f_net(np.dot(x, M))

    H = -np.dot(np.dot(x, M), y)
    H_old = 2*H
    entropies = np.array(H)
    print('x:')
    print(x)
    print('y:')
    print(y)

    while(H > H_old):
        y = f_net(np.dot(x, M))
        x = f_net(np.dot(M, y))
        H_old = H
        H = -np.dot(np.dot(x, M), y)
        entropies = np.append(entropies, H)
        print('x:')
        print(x)
        print('y:')
        print(y)

    return {'x':x, 'y':y, 'entropies':entropies}

M = bam(X=X, Y=Y)

error = 0
for i in range(X.shape[0]):
    print()
    print(i)
    R = bam_evaluate(X[i, :], M)
    
    error = error + np.sqrt( np.sum( np.abs(R['y'] - Y[i]) ) )
    
print(error)


0
x:
[-1 -1  1  1  1 -1  1  1  1 -1]
y:
[-1  1  1 -1 -1  1  1]
x:
[-1 -1  1  1  1 -1  1  1  1 -1]
y:
[-1  1  1 -1 -1  1  1]

1
x:
[ 1 -1  1 -1 -1  1  1  1  1 -1]
y:
[ 1  1 -1 -1 -1 -1  1]
x:
[ 1 -1  1 -1 -1  1  1  1  1 -1]
y:
[ 1  1 -1 -1 -1 -1  1]
0.0
